consumer_key: qSXgYnfl9TQHL0rcRw
consumer_secret: zhzEDv12a87RimkvaisEi5IZvqISzEVmf2gDIJQCuw
oauth_token: 308762265-ahoa4FzpufTaPRghxHsChqwTwMRIRaJfHkmkn5Ip
oauth_token_secret: UwAWZJlhSGiBNgbHtDqiS2ILZJuprd091rUNbETE
websocket_server: ws://bridge.fetcher:8080/